# Generated by Django 4.1.1 on 2024-05-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_details', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('vendor_code', models.CharField(max_length=20, unique=True)),
                ('on_time_delivery_rate', models.FloatField(max_length=20, unique=True)),
                ('quality_rating_avg', models.FloatField(max_length=20, unique=True)),
                ('average_response_time', models.FloatField(max_length=20, unique=True)),
                ('fulfillment_rate', models.FloatField(max_length=20, unique=True)),
            ],
        ),
    ]
